- hosts: terraform-ansible
  tasks:
  - name: instalando o python
    apt:
      pkg:
      - python3
      - virtualenv
      update_cache: yes
    become: yes
  - name: instalando depedencias com pip
    pip:
      virtualenv: /home/ubuntu/tcc/venv
      name:
        - django
        - djangorestframework
  - name: iniciando projeto django
    shell: '. /home/ubuntu/tcc/venv/bin/activate; django-admin startproject setup /home/ubuntu/tcc/' 
  - name: alterando o hosts do settings
    lineinfile:
      path: /home/ubuntu/tcc/setup/settings.py
      regexp: 'ALLOWED_HOSTS'
      line: 'ALLOWED_HOSTS = ["*"]'
      backrefs: yes       
     
