- hosts: terraform-ansible
  tasks:
  - name: Instalando o Python3, virtalenv
    apt:
      pkg:
      - python3 
      - virtualenv
      update_cache: yes
    become: yes
  - name: Instalando depencias com pip
    pip:
      virtualenv: /home/ubuntu/tcc/venv
      name:
      - django
      - djangorestframework
  - name: Verificando se o proketo já existe
    stat:
      path: /home/ubuntu/tcc/setup/settings.py
    register: projeto      
  - name: Iniciando Projeto
    shell: '. /home/ubuntu/tcc/venv/bin/activate; django-admin startproject setup /home/ubuntu/tcc/'
    when: not projeto.stat.exists
  - name: Alterando hosts do setting
    lineinfile: 
      path: /home/ubuntu/tcc/setup/settings.py
      regexp: 'ALLOWED_HOSTS'
      line: 'ALLOWED_HOSTS = ["*"]'
      backrefs: yes          
         
       
      
